name: mudeo
description: a collaborative music video app
version: 0.0.57+57
publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/mudeo-icon.png"
  adaptive_icon_foreground: "assets/images/mudeo-icon.png"
  #adaptive_icon_background: "#000000"
  adaptive_icon_background: "#333C3C"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #camera: 0.9.0
  #camera: ^0.9.4+19
  camera:
    git:
      url: https://github.com/hillelcoren/plugins.git
      path: packages/camera/camera
  camera_macos:
  camera_windows: ^0.2.1+5
  #video_player: ^0.10.12+2
  video_player: ^2.5.3
  video_player_win:
  video_player_macos:
  #native_video_view: 
  path_provider: ^2.0.13
  screen:
  flutter_redux:
  redux_logging:
  http:  ^0.12.2
  shared_preferences:
  built_value:
  built_collection:
  memoize:
  url_launcher:
  cached_network_image:
  share_plus:
  google_sign_in:
  sentry:
  intl:
  font_awesome_flutter:
  #flutter_xlider: 3.4.0
  file_picker: ^5.2.5
  flutter_xlider:
    git:
      url: https://github.com/Ali-Azmoud/flutter_xlider.git
      ref: master
  image_picker:
  chewie:
  #flutter_youtube: ^2.0.0
  draggable_scrollbar:
  flutter_blurhash:
  #in_app_purchase: ^3.1.5
  #rounded_loading_button: 2.0.2
  device_info:
  #tflite: ^1.0.5
  document_analysis:
  visibility_detector:
  #ffmpeg_kit_flutter: ^5.1.0
  ffmpeg_kit_flutter_min_gpl: ^5.1.0
  qr_flutter:
  #esys_flutter_share:
  material_design_icons_flutter:
  permission_handler:
  headset_connection_event:
  flutter_styled_toast: ^2.0.0
  file_saver: ^0.1.1

dependency_overrides:
  platform: ^3.1.0

#dependency_overrides:
  # https://github.com/flutter/flutter/issues/70433#issuecomment-727154345
  #intl: ^0.17.0-nullsafety.2

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  build_runner: ^1.7.2
  built_value_generator: any
  #uild_runner: ^1.2.8
  #built_value_generator: ^6.3.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo-light.png
    - assets/images/logo-dark.png
    - assets/images/apple.png
    - assets/images/google.png
    #- assets/posenet_mv1_075_float_from_checkpoints.tflite
    - assets/tone.mp4

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
