name: mudeo
description: a collaborative music video app
version: 0.0.54+54
publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/mudeo-icon.png"
  adaptive_icon_foreground: "assets/images/mudeo-icon.png"
  #adaptive_icon_background: "#000000"
  adaptive_icon_background: "#333C3C"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #camera: ^0.8.1+3
  camera:
    git:
      url: git://github.com/hillelcoren/plugins.git
      path: packages/camera/camera
  #video_player: ^0.10.12+2
  video_player: 2.1.6
  path_provider: ^1.6.9
  screen: ^0.0.4
  flutter_redux: ^0.8.2
  redux_logging: ^0.5.0
  http: ^0.12.2
  shared_preferences: ^0.5.1+1
  built_value: any
  built_collection: any
  memoize: ^3.0.0
  url_launcher: ^6.0.5
  cached_network_image: ^2.0.0-rc.1
  share: ^2.0.4
  google_sign_in: ^5.0.4
  firebase_auth: ^0.16.1
  sentry: ^3.0.1
  intl: any
  font_awesome_flutter: ^9.1.0
  flutter_xlider: any
  image_picker: ^0.6.4
  chewie: ^1.2.2
  #flutter_youtube: ^2.0.0
  draggable_scrollbar: ^0.1.0
  flutter_blurhash: ^0.5.0
  in_app_purchase: ^0.5.2
  rounded_loading_button: ^1.0.0
  device_info: ^2.0.2
  firebase_analytics: ^5.0.11
  flutter_launcher_icons: ^0.9.0
  video_thumbnail: ^0.3.3
  #tflite: ^1.0.5
  document_analysis: ^0.2.0
  visibility_detector: ^0.2.0
  flutter_ffmpeg: ^0.4.0
  qr_flutter: ^3.2.0
  twitter_qr_scanner: ^1.0.4
  esys_flutter_share: ^1.0.2
  material_design_icons_flutter: ^4.0.5345

#dependency_overrides:
  # https://github.com/flutter/flutter/issues/70433#issuecomment-727154345
  #intl: ^0.17.0-nullsafety.2

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  build_runner: ^1.7.2
  built_value_generator: any
  #uild_runner: ^1.2.8
  #built_value_generator: ^6.3.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo-light.png
    - assets/images/logo-dark.png
    - assets/images/apple.png
    - assets/images/google.png
    - assets/posenet_mv1_075_float_from_checkpoints.tflite
    - assets/tone.mp4

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
